language: node_js
node_js:
  - "9"
cache:
  directories:
    - node_modules
services:
  - postgresql
before_script:
  - psql -c 'create database "todo-example-test";' -U postgres
script:
  - "npm run test"
  - "npm run lint"
after_script:
  - ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/coveralls/bin/coveralls.js